### PR TITLE
New API Added

### PR DESCRIPTION
**Pull request by kbshal**
- Added a new SMS API
- It works for all Nepali numbers

### CODE REVIEW

**Comment by kbshal** [comment]
Hello, any updates?

**Comment by kbshal** [comment]
Waiting for your response @0n1cOn3 @chankruze @priyamharsh14 @TheSpeedX @t0xic0der

**Comment by 0n1cOn3** [comment]
> Waiting for your response @0n1cOn3 @chankruze @priyamharsh14 @TheSpeedX @t0xic0der

Looking for Testers. Till yet, no response in the TBomb Chat.

**Comment by chankruze** [comment]
@kbshal @0n1cOn3 
I'll test tomorrow morning 😁 Code looks good though. Hopefully it'll work ;)

**Comment by 0n1cOn3** [comment]
> @kbshal
> I'll test tomorrow morning 😁 Code looks good though. Hopefully it'll work ;)

That would be awesome! 
Let @TheSpeedX and me know if it does work or partially work or doesn't work!

**Comment by priyamharsh14** [comment]
I got the following response.
```
{"operation": "register_mobile", "success": false, "message": "Error encountered while connecting to SMS Vendor."}
```
Can someone test and verify it?

**Comment by kbshal** [comment]
Haha they prolly detected my activities. I guess I sent total 1000 otp from
that endpoint

**Pull request merged**
