### PR TITLE
Swtechie.sh

### PR DESCRIPTION
**Pull request by Himal9626**
Use this

### CODE REVIEW

**Comment by Himal9626** [comment]
``

**Comment by 0n1cOn3** [comment]
Please add my Mail Adress back pls 😎

You can add your additionally.

0n1cOn3

**Comment by TheSpeedX** [comment]
@Himal9626 Seriously ???
Do You Know What A Contribution is Rather than just sending PRs To Change SpeedX To Your Name

If You Wanna Be A Contributor  Solve Issues From #44  And If its valid We will accept And Add You To Contributors

**Comment by TheSpeedX** [comment]
@Srishivangi  Please Dont post stuff irrelevant to TBomb or this issue

Seeing no good response from @Himal9626 I am closing this PR

**Pull request closed without merging**
