### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by mr-unique-appraiser**

### CODE REVIEW

**Comment by 0n1cOn3** [comment]
Nonsense ? Theres no Requirement with such a high Version!

**Comment by AvinashReddy3108** [comment]
> Nonsense ? Theres no Requirement with such a high Version!

Why even specify the version limits, for such a simple script?

**Comment by 0n1cOn3** [comment]
It has a reason why this has such low versions. 

Im sorry.. We had several "PR" with really nonsense content. Not as would i say, yours is nonsense ;-) 

Lets see, what SpeedX say about that.

**Comment by cclauss** [comment]
The current release of `requests` is v2.24.0 https://requests.readthedocs.io/en/master and https://pypi.org/project/requests

Now that pip has a real dependency resolver, I don't think that it makes sense to mention `urllib3` in requirements.txt or pin its version number because no code in that repo directly imports that module.  Allow the requests maintainers determine if they wish to continue to depend on urllib3 and if so, specify which versions they support.

**Comment by TheSpeedX** [comment]
Currently as per a brand new PR 
There will be pretty much changes in requirements.txt
So unable to merge it

**Comment by TheSpeedX** [comment]
This issue was resolved in #135
This PR will be closed and any further suggestions and improvements are welcomed to dev branch

**Pull request closed without merging**
