### PR TITLE
Added a new sms API

### PR DESCRIPTION
**Pull request by kbshal**
### Added new sms API

- I added a daraz nepal sms api which works for nepali phone numbers

### CODE REVIEW

**Comment by bishalkharel** [comment]
whats the update?

**Comment by TheSpeedX** [comment]
@bishalkharel Thanks for your contribution

**Review by 123hamid456 — COMMENTED** [review]
mesgdcrt.SuccessMessage(version)

**Comment by he7du3h3r77rh4r73hdydu282yrgd** [comment]
Hey brother

**Pull request merged**
