### PR TITLE
Added a new sms API

### PR DESCRIPTION
**Pull request by kbshal**
## Description

# I added the new daraz api for sms
# It only works for nepali phone numbers

### CODE REVIEW

**Comment by 0n1cOn3** [comment]
Looks fine 🙂👌🏻

@TheSpeedX wdym?

**Comment by bishalkharel** [comment]
> Looks fine 🙂👌🏻
> 
> @TheSpeedX wdym?

Where is he?. Why he's not merging my PR

**Comment by TheSpeedX** [comment]
@bishalkharel kindly make a new PR 
Here are some steps you need to follow:
- Put the API in a key "977" (which is Nepals Country code) under the "sms" key.
- Make the value of "977" a list and in it add your API.
- Test it locally

For Example (you can refer this) -
```
{
    "version": "2.3",
    "sms": {
        "977": [
                    --your api dictionary here--
                    ],
       "91":.
..........

```

Putting the api in "91" key will make the api be used for 91 country code.

**Comment by 0n1cOn3** [comment]
> > Looks fine 🙂👌🏻
> 
> > 
> 
> > @TheSpeedX wdym?
> 
> 
> 
> Where is he?. Why he's not merging my PR 

Done 🤓 Read his instructions and youre fine ☺️

**Comment by bishalkharel** [comment]
oops my bad i will make a new PR also sry for late reply 🙂

**Comment by TheSpeedX** [comment]
@bishalkharel any updates ?

**Comment by bishalkharel** [comment]
Oops I forgot about that. I will make a new PR soon bro

**Comment by Valfsr** [comment]
can u add +33 numbers ? (france)

**Comment by 0n1cOn3** [comment]
> can u add +33 numbers ? (france)
> 
> 

The project is no longer under active development. 

Entre-temps, le projet n'est plus en développement actif.

**Pull request merged**
