### PR TITLE
Updating to TBomb v2

### PR DESCRIPTION
**Pull request by TheSpeedX**
Fixed Lot of Issues

And updating to TBomb  from v1.7 to v2
Comes with a Deprecation notice for older versions

Worked on several opened issues in collaboration with @t0xic0der

### TODO
- [x] Test code on various platform and fix any issues

### CODE REVIEW

**Comment by 0n1cOn3** [comment]
I will give you the answer here instead of in Whatsapp. 

macOS and iOS was requested for testing purposes.  
I am making this available.

**Comment by 0n1cOn3** [comment]
iOS Jailbroken: Possible with my iPad on iOS 13.1.3

iOS with iSH; Directly on my iPhone

macOS 11 Beta (Still on B1, its a deprecated Macbook for macOS 11) Macbook9,1

**Comment by t0xic0der** [comment]
Looks good to me. Once the testing is done, we can onload this to `master`, I guess.

**Comment by 0n1cOn3** [comment]
We need some other testings before we should release v2.0. ;-)

➖
Ultragate-Solutions
Stefan Kuny | Inhaber & Gründer
Im Gässli 1
4228 Erschwil

+41763289408
Info@ultragate-solutions.ch
https://ultragate-solutions.ch
________________________________
Von: Akashdeep Dhar <notifications@github.com>
Gesendet: Wednesday, July 29, 2020 11:14:57 AM
An: TheSpeedX/TBomb <TBomb@noreply.github.com>
Cc: 0n1cOn3 <stefankuny@me.com>; Comment <comment@noreply.github.com>
Betreff: Re: [TheSpeedX/TBomb] Updating to TBomb v2 (#135)


Looks good to me. Once the testing is done, we can onload this to master, I guess.

**Pull request merged**
