### PR TITLE
Update TBomb.sh

### PR DESCRIPTION
**Pull request by Devhacm**
for adding sign in program

### CODE REVIEW

**Comment by Devhacm** [comment]
can I add more line in program for adding like mutli sms target, multi call target or multi mail target..

**Comment by Devhacm** [comment]
I want ot add more program in TBomb for adding more multi_sms_target,multi_call_target or multi_mail_target.

**Comment by 0n1cOn3** [comment]
This is a good idea, but it does not look like it in TBomb itself.

**Comment by TheSpeedX** [comment]
No Significant Changes

**Pull request closed without merging**
