### PR TITLE
Refactoring improvements

### LINKED ISSUE #111: Correct existing exit usages with sys.exit() calls
There are 27 noted occurrences of `exit()` which in fact is an incorrect way of leaving a program. `exit()` can be useful in debugging interactive shell programs but you are much better off replacing every call with a `sys.exit()` call (with of-course, an exit code)

### LINKED ISSUE #113: Annoying code clutter due to metadata
The presence of metadata such as those of requests, headers, data, cookies and URLs clutter the code. They can be added to a JSON document and be parsed later during execution. This would also make your script extensible as adding more API endpoints to the script would then become as easy as adding an entry to a JSON document.

### LINKED ISSUE #114: getapi() request calls do not check status before returning boolean value
The request are not examined and most return as true irrespective of the request being successful or not. It is recommended to check the request status or acknowledgement before returning a boolean value to the user stating the status.

### LINKED ISSUE #115: Mobile number hardcoded in AJIO's request
I do not know if it is an expected change but the mobile number in the AJIO's request is hardcoded. You are requested to look into it.

### LINKED ISSUE #126: Many requests are hardcoded to return true
Even if the request might return false with a non-200 code, the script is hardcoded to return `True` on execution for many of the APIs. This must be reworked by analyzing the response code and the response JSON that is received from the server end.

### PR DESCRIPTION
**Pull request by t0xic0der**
This pull request addresses a lot of issues and improves upon them. The changes are listed below.
1.  Acute testing has been done to check compatibility with various Python versions
2.  Fixed #113 - Cleaned up code clutter caused from having country codes and API data 
3.  Shifted away country code information to a JSON file with active reading from there
4.  Shifted away API data to a JSON file - Making API addition and removal processes flexible
5.  Optimized multiple functions to be modular thus making execution about 50% faster
6.  Removed clutter caused by native terminal coloring - Used `colorama` instead
7.  Fixed #126 - Removed hard-coded return in order to check response code for boolean
8.  Fixed #114 - Added status check per request to have more granular detail
9.  Addressed #112 - Redid variable scopes for some but still there are many global variables left
10. Fixed #111 - Replaced all `exit()` calls with `sys.exit()` calls
11. Addressed #108 - Removed some imports but others formed a dependency cycle
12. Fixed #115 - Added variable phone number to the AJIO API data segment
13. Added decorator class per prompt message as it is efficient than manual tabinations
14. Commented auto-updating call for now as a master update might break a branch code
15. Reworked the documentation - Added FOSS points, corrected instructions and typos
16. Added elegant handling of interrupt calls **`[Ctrl]+[C]`** for leaving the script execution

Here are some screenshots of the newly made version.
- Start page
START

- Script in action
RANF2

- Interrupt handling
INTRX

 The files having major changes are 
- `requirements.txt`
- `bombmode.py`
- `isdcodes.json`
- `sitedata.json`

### CODE REVIEW

**Comment by TheSpeedX** [comment]
Hello @t0xic0der ,
It looks  great also there are some optimizations I have to make it as well add an email module to it.

Can you resend your PR to 'dev' branch instead.
So that i can test and do the optimizations and merge

**Comment by t0xic0der** [comment]
Sure thing @TheSpeedX! I would retarget the pull request to the dev branch right away. :slightly_smiling_face:

**Comment by t0xic0der** [comment]
@TheSpeedX, I have come across this warning. Can you confirm if it is normal and that any of the commits I made won't be lost?
Screenshot_2020-07-20 Refactoring improvements by t0xic0der · Pull Request #129 · TheSpeedX TBomb

**Comment by TheSpeedX** [comment]
Yeah You can continue

**Comment by t0xic0der** [comment]
Done. I have set the target branch to `dev`.

**Pull request merged**
