### PR TITLE
PEP8 enhancements

### PR DESCRIPTION
**Pull request by darkestentropy**
* Indentation fixed (converted tabs -> spaces)
* Fixed bare `except`s (discouraged by PEP8)
* Replaced `isdc` and `cnc` lists with `country_codes` map (better code readability)
* Removed ugly `os.system` calls to `echo` colorized text (will be implemented in next commits using Pythonic tools)

### CODE REVIEW

**Comment by TheSpeedX** [comment]
Please Remove logit() calls from the code

**Comment by darkestentropy** [comment]
@TheSpeedX updated.

**Comment by TheSpeedX** [comment]
@darkestentropy Thanks 
Will Try To Completed TODO Soon

**Comment by darkestentropy** [comment]
> Will Try To Completed TODO Soon

No problem, I'll try to help you with that, too.

**Pull request merged**
